### ISSUE TITLE
Are there only plans to add proposed proposals? 

### ISSUE THREAD

**Issue by kylerchin** [barzamin/gtfs-rt#3]
Is there a pathway to adding features from this? https://gtfs.org/realtime/changes/ 

I think maybe feature flags are a good idea?

**Comment by barzamin** [comment]
oh, this is a good idea! i can try to figure out how to build in more protos with feature flags. ~~are transit agencies using any of these in the wild?~~ (nvm, there are definitely producers using at least `trips.wheelchair_accessible` and `LocalizedImage`.)

it looks like these get features get merged into google/transit tip; is there any reason to feature flag them instead of just leaving them as optional in the protobuf as in upstream? unless you're talking about more features not yet merged?

**Comment by kylerchin** [comment]
Yeah I think the features that aren't merged yet could be feature flag structs? I'm not sure exactly how to add those via the current setup. I need to look at the experimental list.

**Comment by barzamin** [comment]
i think there are some broader questions here too: just MTA (using an example I'm familiar with) has:
- [the NYCT subway extension](https://github.com/OneBusAway/onebusaway-gtfs-realtime-api/blob/master/src/main/proto/com/google/transit/realtime/gtfs-realtime-NYCT.proto)
- [LIRR/MNR-specific extensions](https://github.com/OneBusAway/onebusaway-gtfs-realtime-api/blob/master/src/main/proto/com/google/transit/realtime/gtfs-realtime-MTARR.proto)
- [an extension](https://github.com/OneBusAway/onebusaway-gtfs-realtime-api/blob/master/src/main/proto/com/google/transit/realtime/gtfs-realtime-service-status.proto) which provides data from their Mercury service alert CMS

The question them becomes: how can we reasonably choose some set of extensions to add here if there are $n$ providers and $O(n)$ extensions? It's unfortunate that protobuf isn't self-describing, because it truly does mean that every extension or collection thereof needs its own crate/feature/etc.
